apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: agi-beady-gibbon
  name: ui-agi-beady-gibbon
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-740-merge-*
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: agi-beady-gibbon
  name: ui
  namespace: ui-agi-beady-gibbon
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: refs/heads/master
  releaseName: ui
  values:
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: agi-beady-gibbon
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-pull-740-merge-63a27a4c6d141e48ef4cc7afe9fec4b310886005
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    readinessProbe:
      command:
      - echo
      - '0'
      probeType: exec
    replicaCount: 1
    service:
      additionalHosts: false
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: agi-beady-gibbon
  name: api-agi-beady-gibbon
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-372-merge-*
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: agi-beady-gibbon
  name: api
  namespace: api-agi-beady-gibbon
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: refs/heads/master
  releaseName: api
  values:
    biomageCi:
      rdsSandboxId: default
      repo: hms-dbmi-cellenics/api
      sandboxId: agi-beady-gibbon
    hpa:
      enabled: false
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-pull-372-merge-38f2fc1c869b2bcb830ddfde09f93b8d1f2446de
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    readinessProbe:
      path: /v1/health
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: agi-beady-gibbon
  name: worker-agi-beady-gibbon
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-heads-master-*-python
    filter.fluxcd.io/r: glob:refs-heads-master-*-r
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: agi-beady-gibbon
  name: worker
  namespace: worker-agi-beady-gibbon
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/worker
    path: chart-infra/
    ref: cff0fecc5c66f09ee62849b0200a5d0936eaf280
  releaseName: worker
  values:
    kubernetes:
      env: staging
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-cff0fecc5c66f09ee62849b0200a5d0936eaf280-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-cff0fecc5c66f09ee62849b0200a5d0936eaf280-r
      memoryRequest: 4Gi
    replicaCount: 0
    sandboxId: agi-beady-gibbon
    serviceAccount:
      iamRole: worker-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: agi-beady-gibbon
  name: pipeline-agi-beady-gibbon
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/pipelineRunner: glob:refs-heads-master-*-pipeline-runner
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: agi-beady-gibbon
  name: pipeline
  namespace: pipeline-agi-beady-gibbon
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: 9c2617fc954ee29bcaeebf61e96dde5b6ee1b2ee
  releaseName: pipeline
  values:
    clusterEnv: staging
    memoryRequest: 4Gi
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-heads-master-9c2617fc954ee29bcaeebf61e96dde5b6ee1b2ee-pipeline-runner
    replicaCount: 0
    sandboxId: agi-beady-gibbon
    serviceAccount:
      iamRole: pipeline-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
