---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ahriman-droopy-iguana
  name: ui-ahriman-droopy-iguana
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: ahriman-droopy-iguana
  name: ui
  namespace: ui-ahriman-droopy-iguana
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: cf2b1335cd54a1cdaa6e4b0d18825115202221bc
  releaseName: ui
  values:
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: ahriman-droopy-iguana
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-heads-master-8343b846702ce0fb6c719d11ef4fd2b6eafd63bb
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    readinessProbe:
      command:
      - echo
      - '0'
      probeType: exec
    replicaCount: 1
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ahriman-droopy-iguana
  name: api-ahriman-droopy-iguana
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: ahriman-droopy-iguana
  name: api
  namespace: api-ahriman-droopy-iguana
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: cf2b1335cd54a1cdaa6e4b0d18825115202221bc
  releaseName: api
  values:
    biomageCi:
      rdsSandboxId: default
      repo: hms-dbmi-cellenics/api
      sandboxId: ahriman-droopy-iguana
    hpa:
      enabled: false
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-heads-master-c69c0c543f8021171768c090e369076b2f7d23cb
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    readinessProbe:
      path: /v1/health
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ahriman-droopy-iguana
  name: worker-ahriman-droopy-iguana
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-heads-master-*-python
    filter.fluxcd.io/r: glob:refs-heads-master-*-r
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: ahriman-droopy-iguana
  name: worker
  namespace: worker-ahriman-droopy-iguana
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/worker
    path: chart-infra/
    ref: a20eda76cd19578a467e432943bf858b9be1921c
  releaseName: worker
  values:
    kubernetes:
      env: staging
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-a20eda76cd19578a467e432943bf858b9be1921c-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-a20eda76cd19578a467e432943bf858b9be1921c-r
      memoryRequest: 4Gi
    replicaCount: 0
    sandboxId: ahriman-droopy-iguana
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ahriman-droopy-iguana
  name: pipeline-ahriman-droopy-iguana
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/pipelineRunner: glob:refs-pull-239-merge-*-pipeline-runner
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: ahriman-droopy-iguana
  name: pipeline
  namespace: pipeline-ahriman-droopy-iguana
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: refs/pull/239/head
  releaseName: pipeline
  values:
    awsAccountId: '242905224710'
    awsRegion: eu-west-1
    clusterEnv: staging
    memoryRequest: 4Gi
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-pull-239-merge-bc89b293f9dfc535af95bcd582cbeea4d181c4b8-pipeline-runner
    replicaCount: 0
    sandboxId: ahriman-droopy-iguana
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
