apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ahriman-ui744
  name: ui-ahriman-ui744
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-744-merge-*
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: ahriman-ui744
  name: ui
  namespace: ui-ahriman-ui744
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: refs/heads/master
  releaseName: ui
  values:
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: ahriman-ui744
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-pull-744-merge-8b1b3bb29130f419c4d0fb1c9e9e2031f0d0bcf0
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    readinessProbe:
      command:
      - echo
      - '0'
      probeType: exec
    replicaCount: 1
    service:
      additionalHosts: false
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ahriman-ui744
  name: api-ahriman-ui744
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: ahriman-ui744
  name: api
  namespace: api-ahriman-ui744
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: b5c15e19bd94f9dd6fc2e977fac703d9b2f966ce
  releaseName: api
  values:
    biomageCi:
      rdsSandboxId: default
      repo: hms-dbmi-cellenics/api
      sandboxId: ahriman-ui744
    hpa:
      enabled: false
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-heads-master-d317f800cc97c3a848b9688281977ea12703bd5a
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    readinessProbe:
      path: /v1/health
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ahriman-ui744
  name: worker-ahriman-ui744
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-heads-master-*-python
    filter.fluxcd.io/r: glob:refs-heads-master-*-r
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: ahriman-ui744
  name: worker
  namespace: worker-ahriman-ui744
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/worker
    path: chart-infra/
    ref: cff0fecc5c66f09ee62849b0200a5d0936eaf280
  releaseName: worker
  values:
    kubernetes:
      env: staging
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-cff0fecc5c66f09ee62849b0200a5d0936eaf280-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-cff0fecc5c66f09ee62849b0200a5d0936eaf280-r
      memoryRequest: 4Gi
    replicaCount: 0
    sandboxId: ahriman-ui744
    serviceAccount:
      iamRole: worker-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ahriman-ui744
  name: pipeline-ahriman-ui744
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/pipelineRunner: glob:refs-heads-master-*-pipeline-runner
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: ahriman-ui744
  name: pipeline
  namespace: pipeline-ahriman-ui744
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: 95b3dce0799ea1cd9cbf7b0163412be9bd14155b
  releaseName: pipeline
  values:
    clusterEnv: staging
    memoryRequest: 4Gi
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-heads-master-95b3dce0799ea1cd9cbf7b0163412be9bd14155b-pipeline-runner
    replicaCount: 0
    sandboxId: ahriman-ui744
    serviceAccount:
      iamRole: pipeline-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
