---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: grasp6-slimy-mandrill
  name: ui-grasp6-slimy-mandrill
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-725-merge-*
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: grasp6-slimy-mandrill
  name: ui
  namespace: ui-grasp6-slimy-mandrill
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: refs/heads/master
  releaseName: ui
  values:
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: grasp6-slimy-mandrill
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-pull-725-merge-dd65308c2f487cff6f4da3966f1dd0e642e404f1
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    readinessProbe:
      command:
      - echo
      - '0'
      probeType: exec
    replicaCount: 1
    service:
      additionalHosts: false
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: grasp6-slimy-mandrill
  name: api-grasp6-slimy-mandrill
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-363-merge-*
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: grasp6-slimy-mandrill
  name: api
  namespace: api-grasp6-slimy-mandrill
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: refs/heads/master
  releaseName: api
  values:
    biomageCi:
      rdsSandboxId: default
      repo: hms-dbmi-cellenics/api
      sandboxId: grasp6-slimy-mandrill
    hpa:
      enabled: false
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-pull-363-merge-1f671cc8d95f79d48a03e2221dcb5e3dec99d8f7
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    readinessProbe:
      path: /v1/health
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: grasp6-slimy-mandrill
  name: worker-grasp6-slimy-mandrill
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-pull-278-merge-*-python
    filter.fluxcd.io/r: glob:refs-pull-278-merge-*-r
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: grasp6-slimy-mandrill
  name: worker
  namespace: worker-grasp6-slimy-mandrill
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/worker
    path: chart-infra/
    ref: refs/pull/278/head
  releaseName: worker
  values:
    kubernetes:
      env: staging
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-278-merge-1b20da0b54763159fc7d8300de684ed91726b6c3-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-278-merge-1b20da0b54763159fc7d8300de684ed91726b6c3-r
      memoryRequest: 4Gi
    replicaCount: 0
    sandboxId: grasp6-slimy-mandrill
    serviceAccount:
      iamRole: worker-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: grasp6-slimy-mandrill
  name: pipeline-grasp6-slimy-mandrill
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/pipelineRunner: glob:refs-pull-247-merge-*-pipeline-runner
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: grasp6-slimy-mandrill
  name: pipeline
  namespace: pipeline-grasp6-slimy-mandrill
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: refs/pull/247/head
  releaseName: pipeline
  values:
    clusterEnv: staging
    memoryRequest: 4Gi
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-pull-247-merge-8a23cf933b426eeee8a86a94f789394960ca6f78-pipeline-runner
    replicaCount: 0
    sandboxId: grasp6-slimy-mandrill
    serviceAccount:
      iamRole: pipeline-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
