apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: jakub-gkmptrmiosose1t3nzc
  name: ui-jakub-gkmptrmiosose1t3nzc
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: jakub-gkmptrmiosose1t3nzc
  name: ui
  namespace: ui-jakub-gkmptrmiosose1t3nzc
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: 7fb6d2067d1050e8310dff1344f44492f806988a
  releaseName: ui
  values:
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: jakub-gkmptrmiosose1t3nzc
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-heads-master-7672eb5911fd788ec6fb6770cc1190d370b9def9
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    readinessProbe:
      command:
      - echo
      - '0'
      probeType: exec
    replicaCount: 1
    service:
      additionalHosts: false
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: jakub-gkmptrmiosose1t3nzc
  name: api-jakub-gkmptrmiosose1t3nzc
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: jakub-gkmptrmiosose1t3nzc
  name: api
  namespace: api-jakub-gkmptrmiosose1t3nzc
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: 7fb6d2067d1050e8310dff1344f44492f806988a
  releaseName: api
  values:
    biomageCi:
      rdsSandboxId: default
      repo: hms-dbmi-cellenics/api
      sandboxId: jakub-gkmptrmiosose1t3nzc
    hpa:
      enabled: false
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-heads-master-624e66bb1bd6ff70dc204e8b410b5b1adb78466a
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    readinessProbe:
      path: /v1/health
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: jakub-gkmptrmiosose1t3nzc
  name: worker-jakub-gkmptrmiosose1t3nzc
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-heads-master-*-python
    filter.fluxcd.io/r: glob:refs-heads-master-*-r
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: jakub-gkmptrmiosose1t3nzc
  name: worker
  namespace: worker-jakub-gkmptrmiosose1t3nzc
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/worker
    path: chart-infra/
    ref: a20eda76cd19578a467e432943bf858b9be1921c
  releaseName: worker
  values:
    kubernetes:
      env: staging
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-a20eda76cd19578a467e432943bf858b9be1921c-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-a20eda76cd19578a467e432943bf858b9be1921c-r
      memoryRequest: 4Gi
    replicaCount: 0
    sandboxId: jakub-gkmptrmiosose1t3nzc
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: jakub-gkmptrmiosose1t3nzc
  name: pipeline-jakub-gkmptrmiosose1t3nzc
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/pipelineRunner: glob:refs-heads-master-*-pipeline-runner
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: jakub-gkmptrmiosose1t3nzc
  name: pipeline
  namespace: pipeline-jakub-gkmptrmiosose1t3nzc
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: 4e8558522dcdb6bdc7430bf20733bea2a9fd2973
  releaseName: pipeline
  values:
    awsAccountId: '242905224710'
    awsRegion: eu-west-1
    clusterEnv: staging
    memoryRequest: 4Gi
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-heads-master-4e8558522dcdb6bdc7430bf20733bea2a9fd2973-pipeline-runner
    replicaCount: 0
    sandboxId: jakub-gkmptrmiosose1t3nzc
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
