apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-default
  labels:
    sandboxId: default
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/pipelineRunner: glob:refs-heads-master-*-pipeline-runner
  labels:
    sandboxId: default
spec:
  releaseName: pipeline
  chart:
    git: git@github.com:hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: 6513c5937c9b1a7f6fb562b6591de3959923214c
  valuesFrom:
    - configMapKeyRef:
        name: account-config
        namespace: flux
        key: account-config.yaml
  values:
    clusterEnv: staging
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-heads-master-6513c5937c9b1a7f6fb562b6591de3959923214c-pipeline-runner
    sandboxId: default
    memoryRequest: 29Gi
    replicaCount: 1
    serviceAccount:
      iamRole: pipeline-role-staging
