apiVersion: v1
kind: Namespace
metadata:
  name: worker-default
  labels:
    sandboxId: default
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/r: glob:refs-tags-*-r
    filter.fluxcd.io/python: glob:refs-tags-*-python
  labels:
    sandboxId: default
spec:
  releaseName: worker
  chart:
    git: git@github.com:hms-dbmi-cellenics/worker
    path: chart-infra/
    ref: 3c380df7bde5abb4c0c6d87b6d3b0816882f0de3
  valuesFrom:
    - configMapKeyRef:
        name: account-config
        namespace: flux
        key: account-config.yaml
  values:
    kubernetes:
      env: production
    serviceAccount:
      iamRole: worker-role-production
    sandboxId: default
    replicaCount: 2
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-tags-0.25.0-r
      memoryRequest: 28Gi
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-tags-0.25.0-python
