# Template Github AWS IdP setup. This should be run once before deployment.
# Modified from: https://github.com/aws-actions/configure-aws-credentials#sample-iam-oidc-cloudformation-template
AWSTemplateFormatVersion: "2010-09-09"
Description: Set up IAC role using Github OIDC for workflow permissions

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ci-iac-role
      MaxSessionDuration: 7200
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: repo:biomage-org/iac:*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

Outputs:
  Role:
    Value: !GetAtt Role.Arn