AWSTemplateFormatVersion: "2010-09-09"
Description: Set up DNS records for the ELB.

Parameters:
  Environment:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - production
    Description: The environment for which the Route 53 records needs to be created.

  DNSName:
    Type: String
    Description: The URL of the load balancer to deploy.

  DomainName:
    Type: String
    Description: The URL of the domain to apply the change to.

  Route53HostedZoneId:
    Type: String
    Description: The ID of the Route53 hosted zone

  ELBHostedZoneId:
    Type: String
    Description: The ID of the ELB hosted zone

Outputs:
  DomainName:
    Value: !Ref DomainName
    Export:
      Name: !Sub "DomainName-${Environment}"

Resources:
  IngressControllerMapping:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref Route53HostedZoneId
      Comment: !Sub "Routing for Biomage SCP ${Environment} cluster"
      RecordSets:
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          DNSName: !Ref DNSName
          HostedZoneId: !Ref ELBHostedZoneId
      - Name: !Join ['.', ['*', !Ref DomainName]]
        Type: A
        AliasTarget:
          DNSName: !Ref DNSName
          HostedZoneId: !Ref ELBHostedZoneId