apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

# do not add `name` and `region` to this eksctl file. CI will fill these in automatically
metadata:

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: dummy-setup-account
      attachPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Deny
            Action:
              - "s3:*"
            Resource: '*'
    - metadata:
        name: aws-node
        namespace: kube-system
        labels:
          aws-usage: cluster-ops
      attachPolicyARNs:
      - "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"

vpc:
  id: "vpc-0bb100ee731ef5a58"
  subnets:
    private:
      app-us-east-2a:
        id: "subnet-0dcb4e46405522916"
      app-us-east-2b:
        id: "subnet-05b2d2c3c63feed96"
      dmz-us-east-2a:
        id: "subnet-0d951e44b83833d28"
      dmz-us-east-2b:
        id: "subnet-09bccdc8be23d5402"

managedNodeGroups:
  - name: nodegroup-post-scaling-x86-v2
    instanceType: r5.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 80
    privateNetworking: true
    subnets:
      - app-us-east-2a
      - app-us-east-2b
      - dmz-us-east-2a
      - dmz-us-east-2b
    iam:
      withAddonPolicies:
        ebs: true
        autoScaler: true

fargateProfiles:
  - name: worker-default
    selectors:
      - namespace: worker-default
    subnets:
      - subnet-0dcb4e46405522916
      - subnet-05b2d2c3c63feed96
      - subnet-0d951e44b83833d28
      - subnet-09bccdc8be23d5402
  - name: pipeline-default
    selectors:
      - namespace: pipeline-default
    subnets:
      - subnet-0dcb4e46405522916
      - subnet-05b2d2c3c63feed96
      - subnet-0d951e44b83833d28
      - subnet-09bccdc8be23d5402