vpc:
  id: "vpc-0bb100ee731ef5a58"
  subnets:
    private:
      app-us-east-2a:
        id: "subnet-0dcb4e46405522916"
      app-us-east-2b:
        id: "subnet-05b2d2c3c63feed96"
    public:
      dmz-us-east-2a:
        id: "subnet-0d951e44b83833d28"
      dmz-us-east-2b:
        id: "subnet-09bccdc8be23d5402"

managedNodeGroups:
  - name: nodegroup-post-scaling-x86-v2
    subnets:
      - dmz-us-east-2a
      - dmz-us-east-2b

fargateProfiles:
  - name: worker-default
    subnets:
      - subnet-0dcb4e46405522916
      - subnet-05b2d2c3c63feed96

  - name: pipeline-default
    subnets:
      - subnet-0dcb4e46405522916
      - subnet-05b2d2c3c63feed96