{{ if contains "api" .Values.biomageCirepo }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: can-scale-worker-pods
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list", "update", "get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-can-scale-worker-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: can-scale-worker-pods
{{ end }}
