AWSTemplateFormatVersion: "2010-09-09"
Description: Set up AWS Batch for pipelines

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - staging
      - production

Resources:
  BatchComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: !Sub "compute-env-${Environment}"
      State:  ENABLED
      Type: MANAGED
      ReplaceComputeEnvironment: false
      ComputeResources:
        Type: EC2
        AllocationStrategy: BEST_FIT_PROGRESSIVE
        MinvCpus: 0
        DesiredvCpus: 0
        MaxvCpus: 128
        InstanceRole: !Sub "pipeline-instance-profile-${Environment}"
        InstanceTypes:
          - optimal
        SecurityGroupIds:
          - sg-60b63017
        Subnets:
          - subnet-5c7c3a3a
          - subnet-60085928
          - subnet-5337b709

  BatchJobQueue:
    Type: AWS::Batch::JobQueue
    DependsOn: BatchComputeEnvironment
    Properties:
      JobQueueName: !Sub "queue-pipeline-${Environment}"
      Priority: 1
      ComputeEnvironmentOrder:
        - ComputeEnvironment: !Sub "compute-env-${Environment}"
          Order: 1
      State: ENABLED

  BatchPipelineJob:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: !Sub "job-pipeline-${Environment}"
      ContainerProperties:
        Command:
          - Rscript
          - init.R
        Image: !Sub "242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:batch-${Environment}"
        ResourceRequirements:
          - Type: VCPU
            Value: 2
          - Type: MEMORY
            Value: 8192 # MiB
      Type: Container