AWSTemplateFormatVersion: "2010-09-09"
Description: Set up permissions for bioinformatics [managed by github.com/biomage-org/iac]

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - staging
      - production
    Description: The environment for which the access group is created.

Resources:
  BioinformaticsAccessGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub "bioinformatics-${Environment}-access"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Policies:
        - PolicyName: !Sub "can-upload-${Environment}-source"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                Resource:
                  - !Sub "arn:aws:s3:::biomage-originals-${Environment}-${AWS::AccountId}/*"
                  - !Sub "arn:aws:s3:::biomage-source-${Environment}-${AWS::AccountId}/*"
                  - "arn:aws:s3:::cf-templates-*"

