Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - staging
      - production
    Description: The environment for which the access group is created.

Resources:
  CanLookAtRdsInfrastructurePolicy:
    Type: AWS::IAM::Policy
    Properties:
      Groups: 
        - !Sub "engineer-${Environment}-access"
      PolicyName: "can-look-at-rds-infrastructure"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "rds:DescribeClusters"
              - "rds:DescribeDBClusterEndpoints"
              - "rds:DescribeDBProxyTargetGroups"
              - "rds:DescribeDBInstanceAutomatedBackups"
              - "rds:DescribeGlobalClusters"
              - "rds:DescribeEngineDefaultParameters"
              - "rds:DescribeRecommendations"
              - "rds:DescribeDBProxyTargets"
              - "rds:DownloadDBLogFilePortion"
              - "rds:DescribeSourceRegions"
              - "rds:DescribeDBSnapshots"
              - "rds:DescribeDBSecurityGroups"
              - "rds:DescribeReservedDBInstances"
              - "rds:DescribeValidDBInstanceModifications"
              - "rds:DescribeOrderableDBInstanceOptions"
              - "rds:DescribeCertificates"
              - "rds:DescribeOptionGroups"
              - "rds:DescribeDBEngineVersions"
              - "rds:DescribeDBSubnetGroups"
              - "rds:DescribeExportTasks"
              - "rds:DescribePendingMaintenanceActions"
              - "rds:DescribeDBParameterGroups"
              - "rds:DescribeDBClusterBacktracks"
              - "rds:DescribeReservedDBInstancesOfferings"
              - "rds:DescribeRecommendationGroups"
              - "rds:DescribeDBInstances"
              - "rds:DescribeEngineDefaultClusterParameters"
              - "rds:DescribeDBProxies"
              - "rds:DescribeDBParameters"
              - "rds:DescribeEventCategories"
              - "rds:DescribeDBProxyEndpoints"
              - "rds:DescribeEvents"
              - "rds:DescribeDBClusterSnapshotAttributes"
              - "rds:DescribeDBClusterParameters"
              - "rds:DescribeEventSubscriptions"
              - "rds:DescribeDBLogFiles"
              - "rds:DescribeDBSnapshotAttributes"
              - "rds:DescribeDBClusterSnapshots"
              - "rds:DescribeOptionGroupOptions"
              - "rds:DownloadCompleteDBLogFile"
              - "rds:DescribeDBClusterEndpoints"
              - "rds:DescribeDBClusters"
              - "rds:DescribeAccountAttributes"
              - "rds:DescribeDBClusterParameterGroups"
            Resource: "*"

  CanConnectToRdsDb:
    Type: AWS::IAM::Policy
    Properties:
      Groups: 
        - !Sub "engineer-${Environment}-access"
      PolicyName: "can-connect-to-rds"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - rds-db:connect
            Resource:
              - !Sub "arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:aurora-cluster-${Environment}-*/dev_role"
          - Effect: Allow
            Action:
              - rds:DescribeGlobalClusters
            Resource:
              - !Sub "arn:aws:rds:${AWS::Region}:${AWS::AccountId}:global-cluster:*"
          - Effect: Allow
            Action:
              - rds:DescribeClusters
              - rds:DescribeDBClusterEndpoints
            Resource:
              - !Sub "arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:aurora-cluster-${Environment}"

  CanConnectToRdsAgent:
    Type: AWS::IAM::Policy
    Properties:
      Groups: 
        - !Sub "engineer-${Environment}-access"
      PolicyName: !Sub "can-connect-to-rds-agent-${Environment}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: ec2:DescribeInstances
            Resource: "*"
          - Effect: Allow
            Action:
              - ec2-instance-connect:SendSSHPublicKey
              - ec2-instance-connect:SendSerialConsoleSSHPublicKey
            Resource:
              - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/*
            Condition:
              StringEquals:
                ec2:ResourceTag/Name: !Sub rds-${Environment}-ssm-agent
          - Effect: Allow
            Action: 
              - ssm:StartSession
              - ssm:TerminateSession
            Resource: 
              - !Sub arn:aws:ssm:${AWS::Region}::document/AWS-StartSSHSession
              - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/*

  CanRestoreRdsDb:
    Type: AWS::IAM::Policy
    Properties:
      Groups: 
        - !Sub "engineer-${Environment}-access"
      PolicyName: "can-perform-rds-point-in-time-restores"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - rds:ModifyDBInstance
              - rds:ModifyDBCluster
              - rds:CreateDBInstance
              - rds:CreateDBCluster
              - rds:ListTagsForResource
              - rds:RestoreDBClusterToPointInTime
              - rds:RestoreDBInstanceToPointInTime
            Resource:
              - !Sub "arn:aws:rds:${AWS::Region}:${AWS::AccountId}:*"
          - Effect: Allow
            Action:
              - ec2:DescribeSecurityGroups
              - ec2:DescribeVpcs
              - ec2:DescribeAccountAttributes
            Resource: "*"
