AWSTemplateFormatVersion: "2010-09-09"
Description: Set up SNS topics for Cellenics [managed by github.com/biomage-org/iac]

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - staging
      - production
    Description: The environment for which the SNS topic needs to be created.
  SandboxID:
    Type: String
    Default: default
    Description: The sandbox ID of the environment that this topic is created for.

Conditions:
  isProd: !Equals [!Ref Environment, "production"]
  isDev: !Equals [!Ref Environment, "development"]

Resources:
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: true
      DeduplicationScope: "messageGroup"
      FifoQueue: true
      QueueName: !If [isDev, "development-queue.fifo", !Sub "queue-job-${SandboxID}-${Environment}.fifo"]
      FifoThroughputLimit: "perMessageGroupId"

  SNSTopicV2:
    Type: AWS::SNS::Topic
    Properties:
      KmsMasterKeyId: "alias/aws/sns"
      TopicName: !Sub "work-results-${Environment}-${SandboxID}-v2"

  SNSEndpointLambdaSubcription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Ref SNSTopicV2
      Protocol: "lambda"
      Endpoint:
        # Sandbox id for the subscription is set to default because right now
        # there is only 1 endpoint Lambda instance for each environment
        Fn::ImportValue: !Sub "sns-endpoint-lambda-${Environment}-default-v2::ARN"
      DeliveryPolicy:
        healthyRetryPolicy:
          minDelayTarget: 10
          maxDelayTarget: 60
          numRetries: 56
          numNoDelayRetries: 0
          numMinDelayRetries: 2
          numMaxDelayRetries: 16
          backoffFunction: exponential