AWSTemplateFormatVersion: "2010-09-09"
Description: Set up SNS topics for Cellenics [managed by github.com/biomage-org/iac]

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - staging
      - production
    Description: The environment for which the SNS topic needs to be created.
  SandboxID:
    Type: String
    Default: default
    Description: The sandbox ID of the environment that this topic is created for.

Conditions:
  isDev: !Equals [!Ref Environment, "development"]

Resources:
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: true
      DeduplicationScope: "messageGroup"
      FifoQueue: true
      QueueName: !If [isDev, "development-queue.fifo", !Sub "queue-job-${SandboxID}-${Environment}.fifo"]
      FifoThroughputLimit: "perMessageGroupId"
      SqsManagedSseEnabled: true

  SNSTopicV2:
    Type: AWS::SNS::Topic
    Properties:
      KmsMasterKeyId: "alias/aws/sns"
      TopicName: !Sub "work-results-${Environment}-${SandboxID}-v2"

Outputs:
  SNSTopicV2Arn:
    Description: The ARN of the SNS v2 topic
    Value: !Ref SNSTopicV2
    Export:
      Name: !Sub "sns-work-results-${Environment}-${SandboxID}-v2::ARN"
