name: Load Deployment Config

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: "Environment for validation (leave blank to skip validation)"
        required: false

  workflow_call:
    inputs:
      environment:
        type: string
        description: "Environment for validation (leave blank to skip validation)"
        required: false
    outputs:
      config:
        description: "Configuration data for the current organization"
        value: ${{ jobs.setup.outputs.config }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.load_variables.outputs.config }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

      ### DELETE BEFORE MERGING
      with: 
        ref: hms-merge

    - id: load_variables
      name: Load variables
      run: |
        CONFIG=$(cat deployment-config.json | jq -r --arg org "${{ github.repository_owner }}" '.[$org]')
        echo "{config}={$CONFIG}" >> $GITHUB_OUTPUT

  validate-environment-name:
    name: Validate selected option
    needs: setup
    if: ${{ github.event.inputs.environment != '' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

        ### DELETE BEFORE MERGING
        with: ####
          ref: hms-merge ###
          
      - name: Validate input against config
        run: |
          CONFIG='${{ needs.setup.outputs.config }}'
          ENVIRONMENT_INPUT="${{ github.event.inputs.environment }}"
          ENVIRONMENTS=$(echo $CONFIG | jq -r '.environment_names')
          
          if [[ "$ENVIRONMENTS" =~ "$ENVIRONMENT_INPUT" ]] || [[ "$ENVIRONMENT_INPUT" == "all" ]]; then
            echo "Valid option selected"
            exit 0
          else
            echo "Invalid option selected"
            exit 1
          fi
